env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - xo-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: ['./vite.config.ts']
    parserOptions:
      project: './tsconfig.node.json'
plugins:
  - react
settings:
  react:
    version: detect
rules: {}
